@echo off
title Launching SoupOS...
set BUILDDIR=%0/../bin
set OVMFDIR=%0/../../OVMFbin
@pushd %~dp0
color 0a
cd C:\Windows\System32
echo Initializing WSL...
wsl exit
echo Starting WSL....
echo Starting Build....
wsl cd SoupOSUEFI ; cd gnu-efi ; make bootloader ; cd ../kernel ; make kernel ; make buildimg
echo Build Complete....
echo Fixing QEMU...
echo Removing Broken Files...
wsl cd SoupOSUEFI/OVMFbin ; rm -f OVMF_CODE-pure-efi.fd OVMF_CODE-pure-efi.fdZone.Identifier OVMF_VARS-pure-efi.fd OVMF_VARS-pure-efi.fdZone.Identifier
echo Replacing Old Files...
wsl cd SoupOSUEFI/OVMFbinSrc ; cp -f OVMF_CODE-pure-efi.fd ../OVMFbin/OVMF_CODE-pure-efi.fd ; cp -f OVMF_VARS-pure-efi.fd ../OVMFbin/OVMF_VARS-pure-efi.fd
echo Starting QEMU....
@set path=C:\Program Files\qemu
qemu-system-x86_64 -drive format=raw,file=Z:\home\soupman\SoupOSUEFI\kernel\bin\SoupOS.img -m 256M -cpu qemu64 -drive if=pflash,format=raw,unit=0,file=..\OVMFbin\OVMF_CODE-pure-efi.fd,readonly=on -drive if=pflash,format=raw,unit=1,file=..\OVMFbin\OVMF_VARS-pure-efi.fd -net none
@popd